spring.cloud.gateway.discovery.locator.enabled=true

# Route ??? shopping-cart
spring.cloud.gateway.routes[0].id=shopping-cart-route
spring.cloud.gateway.routes[0].uri=lb://shopping-cart
spring.cloud.gateway.routes[0].predicates[0]=Path=/shopping-cart/**
spring.cloud.gateway.routes[0].filters[0]=PrefixPath=/api/v1

# Route ??? shopping-store ? RETRY
spring.cloud.gateway.routes[1].id=shopping-store-route
spring.cloud.gateway.routes[1].uri=lb://shopping-store
spring.cloud.gateway.routes[1].predicates[0]=Path=/shopping-store/**
spring.cloud.gateway.routes[1].filters[0]=PrefixPath=/api/v1
# RETRY ?????? ??? ProductNotFoundException
spring.cloud.gateway.routes[1].filters[1]=name=Retry, args={retries=3, statuses=NOT_FOUND, exceptions=ru.yandex.practicum.dto.exceptions.ProductNotFoundException, methods=GET, series=SERVER_ERROR}

# Route ??? warehouse
spring.cloud.gateway.routes[2].id=warehouse-route
spring.cloud.gateway.routes[2].uri=lb://warehouse
spring.cloud.gateway.routes[2].predicates[0]=Path=/warehouse/**
spring.cloud.gateway.routes[2].filters[0]=PrefixPath=/api/v1

# Route ??? order
spring.cloud.gateway.routes[3].id=order-route
spring.cloud.gateway.routes[3].uri=lb://order
spring.cloud.gateway.routes[3].predicates[0]=Path=/order/**
spring.cloud.gateway.routes[3].filters[0]=PrefixPath=/api/v1

# Route ??? payment
spring.cloud.gateway.routes[4].id=payment-route
spring.cloud.gateway.routes[4].uri=lb://payment
spring.cloud.gateway.routes[4].predicates[0]=Path=/payment/**
spring.cloud.gateway.routes[4].filters[0]=PrefixPath=/api/v1

# Route ??? delivery
spring.cloud.gateway.routes[5].id=delivery-route
spring.cloud.gateway.routes[5].uri=lb://delivery
spring.cloud.gateway.routes[5].predicates[0]=Path=/delivery/**
spring.cloud.gateway.routes[5].filters[0]=PrefixPath=/api/v1

server.port=8080
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/