spring:
datasource:
  url: jdbc:postgresql://postgres:5432/smarthome
  username: postgres
  password: postgres
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
resilience4j:
  circuitbreaker:
    instances:
      warehouseService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s