spring.datasource.url=jdbc:postgresql://postgres:5432/smarthome
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082
eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
resilience4j.circuitbreaker.instances.warehouseService.sliding-window-size=10
resilience4j.circuitbreaker.instances.warehouseService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.warehouseService.wait-duration-in-open-state=10s
