spring:
  application:
    name: collector

grpc:
  server:
    port: 59091  # ИЗМЕНИТЬ с 9090 на 59091

kafka:
  bootstrap-servers: localhost:9092
  topics:
    sensors: telemetry.sensors.v1
    hubs: telemetry.hubs.v1

logging:
  level:
    ru.yandex.practicum: DEBUG
    org.apache.kafka: INFO
    net.devh: DEBUG