spring:
  application:
    name: shopping-cart
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.uuid}

resilience4j:
  circuitbreaker:
    instances:
      warehouseService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers