spring:
  config:
    activate:
      on-profile: ci
  application:
    name: analyzer
  datasource:
    url: jdbc:postgresql://postgres:5432/smarthome
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

grpc:
  client:
    hub-router:
      address: 'static://hub-router:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
      maxInboundMessageSize: 10485760
      connectTimeout: 30s
      maxAttempts: 5
      retryDelay: 1s

kafka:
  bootstrap-servers: kafka:29092
  consumer:
    hub-events:
      group-id: analyzer-hub-events-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 10
    snapshots:
      group-id: analyzer-snapshots-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 10
  topics:
    hub-events: telemetry.hubs.v1
    snapshots: telemetry.snapshots.v1

logging:
  level:
    ru.yandex.practicum: DEBUG
    io.grpc: DEBUG
    net.devh: DEBUG