spring:
  config:
    activate:
      on-profile: default
  application:
    name: analyzer
  datasource:
    url: jdbc:postgresql://localhost:5432/smarthome
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

# Дублируем настройки Kafka для default профиля
kafka:
  bootstrap-servers: localhost:9092
  consumer:
    hub-events:
      group-id: analyzer-hub-events-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 1
    snapshots:
      group-id: analyzer-snapshots-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 1
  topics:
    hub-events: telemetry.hubs.v1
    snapshots: telemetry.snapshots.v1

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
      maxInboundMessageSize: 10485760

logging:
  level:
    ru.yandex.practicum: DEBUG